# mxc: path=/home/metaory/.config/kitty/kittheme.conf
# mxc: path=/home/metaory/.config/mxc/term-kitty-colors.conf

#  ░░░░░▒▒▒▒▒▓▓▓▓█━╸made with╺━█▓▓▓▓▒▒▒▒▒░░░░░
#  ░░ https://github.com/metaory/confsubst  ░░
#  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

background           #220033
foreground           #6655FF

mark1_background     #EE3377
mark1_foreground     black
mark2_background     #33CC55
mark2_foreground     black
mark3_background     #AACC22
mark3_foreground     black

bell_border_color    #EE3377

selection_background #4411BB
selection_foreground #44DDFF

# cursor_text_color    #002211
# cursor               #229911

color0               #331166
color1               #EE3377
color2               #33CC55
color3               #AACC22
color4               #4433CC
color5               #6611CC
color6               #33DDBB
color7               #AA99EE
color8               #441A55
color9               #FF4488
color10              #44DD66
color11              #BBDD33
color12              #4444DD
color13              #6611DD
color14              #44EECC
color15              #BBAAEE
